# Generated by Django 4.0.2 on 2022-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomUser', '0002_feedback_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
