# Generated by Django 4.0.2 on 2022-03-05 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0016_alter_customer_phone'),
        ('EcomUser', '0003_alter_feedback_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('display_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.product_varients')),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['-created'],
            },
        ),
    ]
