# Generated by Django 4.0.2 on 2022-02-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=20)),
            ],
        ),
    ]
