# Generated by Django 4.0.2 on 2022-02-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Banners',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Catogory',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
        migrations.DeleteModel(
            name='Pincode',
        ),
        migrations.DeleteModel(
            name='VarientType',
        ),
        migrations.DeleteModel(
            name='VarientValues',
        ),
        migrations.AlterModelOptions(
            name='adminrole',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AddField(
            model_name='adminrole',
            name='Created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='role_name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterModelTable(
            name='adminrole',
            table='AdminRole',
        ),
    ]
