# Generated by Django 4.0.2 on 2022-02-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0002_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banner_url',
            field=models.URLField(max_length=100),
        ),
    ]
