# Generated by Django 4.0.2 on 2022-02-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0003_area_banners_brand_customer_offers_varienttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='role_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20),
        ),
    ]
