# Generated by Django 4.0.2 on 2022-02-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0003_productimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table=None,
        ),
    ]
