# Generated by Django 4.0.2 on 2022-02-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0003_alter_banners_banner_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_image', models.FileField(upload_to='images/brand')),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
    ]
