# Generated by Django 4.0.2 on 2022-02-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0004_alter_adminrole_role_name_alter_adminrole_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadmin',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.adminrole'),
        ),
    ]
