# Generated by Django 4.0.2 on 2022-02-08 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogory_name', models.CharField(max_length=100)),
                ('catogory_image', models.FileField(upload_to='images/catogory')),
                ('display_order', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.catogory')),
            ],
            options={
                'db_table': 'Catogory',
            },
        ),
    ]
