# Generated by Django 4.0.2 on 2022-02-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0005_catogory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient_name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='VarientValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient_values', models.CharField(max_length=100)),
                ('display_order', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('varient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.varienttype')),
            ],
        ),
    ]
