# Generated by Django 4.0.2 on 2022-02-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0005_alter_customadmin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadmin',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
