# Generated by Django 4.0.2 on 2022-02-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0006_alter_customadmin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmin',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
