# Generated by Django 4.0.2 on 2022-02-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0006_varienttype_brand_status_varientvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(upload_to='images/brand'),
        ),
    ]
