# Generated by Django 4.0.2 on 2022-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0007_alter_customer_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='catogory',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='offers',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=30),
        ),
        migrations.AlterField(
            model_name='varienttype',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='varientvalues',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
