# Generated by Django 4.0.2 on 2022-02-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0007_customadmin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('Created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Main Path',
                'ordering': ['-Created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customadmin',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AddField(
            model_name='customadmin',
            name='Created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SubPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('display_order', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now=True)),
                ('main_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.mainpath')),
            ],
            options={
                'db_table': 'Sub Path',
                'ordering': ['-Created_at'],
            },
        ),
    ]
