# Generated by Django 4.0.2 on 2022-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0008_alter_brand_status_alter_catogory_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupenCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('discount', models.IntegerField()),
                ('disc_type', models.CharField(choices=[('Amount', 'Amount'), ('Percentage', 'Percentage')], max_length=20)),
                ('usercount', models.PositiveIntegerField()),
                ('min_amount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CoupenCode',
            },
        ),
    ]
