# Generated by Django 4.0.2 on 2022-02-14 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0008_mainpath_alter_customadmin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customadmin',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.adminrole'),
        ),
    ]
