# Generated by Django 4.0.2 on 2022-02-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0009_alter_customadmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='permissions',
            field=models.ManyToManyField(to='EcomAdmin.SubPath'),
        ),
    ]
