# Generated by Django 4.0.2 on 2022-02-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0009_coupencode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupencode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
