# Generated by Django 4.0.2 on 2022-02-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0009_alter_brand_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('offer_image', models.ImageField(upload_to='images/offers')),
                ('offer_app_image', models.ImageField(upload_to='images/offers/app_image')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=30)),
            ],
            options={
                'db_table': 'Offers',
            },
        ),
        migrations.AlterModelTable(
            name='varienttype',
            table='Varient Type',
        ),
        migrations.AlterModelTable(
            name='varientvalues',
            table='Varient Values',
        ),
    ]
