# Generated by Django 4.0.2 on 2022-02-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0010_alter_coupencode_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupencode',
            name='is_active',
        ),
    ]
