# Generated by Django 4.0.2 on 2022-02-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0011_area_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.area'),
        ),
    ]
