# Generated by Django 4.0.2 on 2022-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0011_alter_adminrole_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='EcomAdmin.SubPath'),
        ),
    ]
