# Generated by Django 4.0.2 on 2022-02-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0012_alter_adminrole_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('state', models.CharField(choices=[('kerala', 'kerala')], max_length=20)),
                ('district', models.CharField(choices=[('kozhikode', 'kozhikode')], max_length=20)),
                ('landmark', models.TextField(max_length=200)),
                ('country', models.CharField(choices=[('india', 'india')], max_length=20)),
                ('default', models.BooleanField(default=False)),
                ('address_type', models.CharField(choices=[('home', 'home'), ('work', 'work')], max_length=20)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.pincode')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.customer')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Product_Varients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Varient_name', models.CharField(max_length=255)),
                ('Selling_Prize', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Display_Prize', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Product_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('Product_Offers', models.ManyToManyField(blank=True, to='EcomAdmin.Offers')),
                ('Varient_Values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.varientvalues')),
            ],
            options={
                'db_table': 'Product_Varients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Description', models.TextField()),
                ('Thumbnail_image', models.FileField(upload_to='Products')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Product_Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.brand')),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.catogory')),
                ('Product_Items', models.ManyToManyField(blank=True, to='EcomAdmin.Product_Varients', verbose_name='ProductItems')),
                ('Varient_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.varienttype')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalcount', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(choices=[('COD', 'COD'), ('PAYMENT', 'PAYMENT')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], max_length=20)),
                ('platform', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.orderdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcomAdmin.product')),
            ],
        ),
    ]
