# Generated by Django 4.0.2 on 2022-02-09 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0013_remove_brand_brand_image_remove_brand_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['Created_at']},
        ),
        migrations.AddField(
            model_name='brand',
            name='Created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 2, 9, 11, 56, 51, 620295, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(default=False, upload_to='images/brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='banners',
            name='Created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
