# Generated by Django 4.0.2 on 2022-02-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0013_address_product_varients_product_orderdetails_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
