# Generated by Django 4.0.2 on 2022-02-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0014_alter_brand_options_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_image',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='status',
        ),
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
    ]
