# Generated by Django 4.0.2 on 2022-03-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0014_alter_customer_conf_password_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
