# Generated by Django 4.0.2 on 2022-02-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0014_alter_address_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Thumbnail_image',
            field=models.FileField(null=True, upload_to='Products'),
        ),
    ]
