# Generated by Django 4.0.2 on 2022-02-10 03:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0015_alter_brand_options_remove_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AddField(
            model_name='brand',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 10, 3, 39, 7, 258314, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(default=False, upload_to='images/brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='Brand',
        ),
    ]
