# Generated by Django 4.0.2 on 2022-02-10 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0017_alter_catogory_options_catogory_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AddField(
            model_name='offers',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 10, 6, 41, 1, 44381, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
