# Generated by Django 4.0.2 on 2022-03-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0017_alter_address_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.CharField(max_length=100),
        ),
    ]
