# Generated by Django 4.0.2 on 2022-02-10 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0018_alter_offers_options_offers_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varienttype',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AlterModelOptions(
            name='varientvalues',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AddField(
            model_name='varienttype',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 10, 7, 16, 42, 632786, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='varientvalues',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 10, 7, 16, 54, 257069, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
