# Generated by Django 4.0.2 on 2022-02-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0019_alter_varienttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogory',
            name='catogory_image',
            field=models.ImageField(upload_to='images/catogory'),
        ),
    ]
