# Generated by Django 4.0.2 on 2022-03-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0019_alter_address_address_type_alter_address_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
