# Generated by Django 4.0.2 on 2022-03-11 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0020_alter_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_varients',
            name='Product_Offers',
        ),
        migrations.AddField(
            model_name='offers',
            name='Product_Offers',
            field=models.ManyToManyField(blank=True, to='EcomAdmin.Product_Varients'),
        ),
        migrations.AddField(
            model_name='offers',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
