# Generated by Django 4.0.2 on 2022-02-10 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0020_alter_catogory_catogory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AlterModelOptions(
            name='pincode',
            options={'ordering': ['-Created_at']},
        ),
        migrations.AddField(
            model_name='area',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincode',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
