# Generated by Django 4.0.2 on 2022-02-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0021_alter_area_options_alter_pincode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='postoffice',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
