# Generated by Django 4.0.2 on 2022-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0022_pincode_postoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=30),
        ),
    ]
