# Generated by Django 4.0.2 on 2022-03-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0023_auto_20220313_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_product',
            field=models.ManyToManyField(blank=True, null=True, to='EcomAdmin.Product'),
        ),
    ]
