# Generated by Django 4.0.2 on 2022-02-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0023_alter_area_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default=False, max_length=30),
            preserve_default=False,
        ),
    ]
