# Generated by Django 4.0.2 on 2022-03-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0024_product_related_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Razorpay_order_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Razorpay_payment_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Razorpay_signature',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
