# Generated by Django 4.0.2 on 2022-02-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0024_pincode_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=20)),
                ('conf_password', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['-registered_date'],
            },
        ),
    ]
