# Generated by Django 4.0.2 on 2022-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0025_orderdetails_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='session_id',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
