# Generated by Django 4.0.2 on 2022-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0026_rename_name_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='is_intermediate',
            field=models.BooleanField(default=True),
        ),
    ]
