# Generated by Django 4.0.2 on 2022-03-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0026_customer_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='session_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
