# Generated by Django 4.0.2 on 2022-02-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0027_banners_is_intermediate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='bannner_name',
            new_name='banner_name',
        ),
    ]
