# Generated by Django 4.0.2 on 2022-02-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0028_rename_bannner_name_banners_banner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['-Created_at']},
        ),
    ]
