# Generated by Django 4.0.2 on 2022-03-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0028_rename_first_name_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_varients',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='EcomAdmin.product'),
        ),
    ]
