# Generated by Django 4.0.2 on 2022-02-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0029_alter_banners_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
