# Generated by Django 4.0.2 on 2022-03-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAdmin', '0033_remove_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order',
        ),
    ]
